import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { Navbar } from "@/components/navbar"
import { ThemeProvider } from "@/components/providers"
import { Sidebar } from "@/components/sidebar"
import { docsConfig } from "@/config/docs"

import "../styles/globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full w-full">
      <head />
      <body
        className={`bg-ui-bg-base h-full max-h-screen w-full ${inter.className}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          <div className="w-full">
            <Navbar />
            <div className="lg:max-w-xxl grid w-full grid-cols-1 px-1.5 lg:mx-auto lg:grid-cols-[280px_1fr]">
              <Sidebar items={docsConfig.sidebarNav} />
              <div className="relative flex w-full flex-1 items-start justify-center px-3 py-6 md:px-8 lg:px-16 lg:py-[112px]">
                <main className="h-full w-full lg:max-w-[720px] lg:px-px">
                  {children}
                </main>
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
